name: Deploy VMs

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      intent:
        type: choice
        description: "Intent of running Terraform workflow"
        default: plan
        options:
          - plan
          - apply

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    name: Deploy Scaffolding Resources
    env:
      PROXMOX_VE_INSECURE: true
      PROXMOX_VE_USERNAME: ${{ secrets.PROXMOX_VE_USERNAME }}
      PROXMOX_VE_PASSWORD: ${{ secrets.PROXMOX_VE_PASSWORD }}
      PROXMOX_VE_ENDPOINT: ${{ secrets.PROXMOX_VE_SERVER }}
      TF_VAR_network: ${{ vars.NETWORK }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_CLIENT_SECRET }}
          tags: tag:github-actions

      
